version: '3.6'

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:27017